image: craigkai/ke-gui:latest

stages:
  - test

  # Cache modules in between jobs
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - .venv/

before_script:
  - export DISPLAY=:99.0;
  - pip3 install -r requirements.txt
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX

Unit Tests:
    stage: test
    script:
      - python3 -m pytest tests
