name: Python application

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    # Setup Python (faster than using Python container)
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install pipenv
      run: |
            python -m pip install --upgrade pipenv wheel
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
        pipenv install --deploy --dev
    - name: Install latest pip, setuptools, wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel --upgrade-strategy=eager

    - name: Install OS dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libmtdev1
        sudo apt-get -y install libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev
        sudo apt-get -y install build-essential libgl1-mesa-dev libgles2-mesa-dev
        sudo apt install rustc pipenv

    - name: Install pipenv via pip
      run: |
        python3 -m pip install --cache-dir cache/pip --upgrade pip
        python3 -m pip install pipenv

    - name: Install Python dependencies
      run: |
        make install

    - name: Run Rust tests
      run: |
        cd libdigitaldash/
        cargo test

    - name: Run Python tests
      run: |
        export DISPLAY=:99.0;
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
        make test

    - name: Run Linting
      run: |
        make lint
        make clean
